webrtc: true
rtsp: true
hls: false

webrtcICEServers2:
  - url: stun:home.amtrend.ru:3478
  - url: turn:home.amtrend.ru:3478
    username: webrtcuser
    password: webrtcpass

webrtc:
  iceTimeout: 30
  dtlsTimeout: 30
  maxLate: 100
  maxBufferSize: 1048576
  jitterBufferSize: 200

paths:
  cam_entrance:
    source: rtsp://admin:admin@192.168.0.20/live
    readBufferSize: 2097152
    reconnect: true
    reconnectInterval: 10
  cam_back_entrance:
    source: rtsp://admin:admin@192.168.0.19/live
    readBufferSize: 2097152
    reconnect: true
    reconnectInterval: 10