webrtc: true
rtsp: true
hls: false

webrtcICEServers2:
  - url: stun:home.amtrend.ru:3478

paths:
  cam_entrance:
    source: rtsp://admin:admin@192.168.0.20/live
  cam_back:
    source: rtsp://admin:admin@192.168.0.19/live
