webrtc: true
rtsp: true
hls: false

webrtcICEServers:
  - url:
    - stun:stun.l.google.com:19302

paths:
  cam_entrance:
    source: rtsp://admin:admin@192.168.0.20/live
  cam_back:
    source: rtsp://admin:admin@192.168.0.19/live
