server:
  webrtcIceServers:
    - urls: [stun:coturn:3478]
  rtsp: yes
  hls: no
  webrtc: yes

paths:
  cam_entrance:
    source: rtsp://admin:admin@192.168.0.20/live
  cam_back:
    source: rtsp://admin:admin@192.168.0.19/live