webrtc: true
rtsp: true
hls: false

webrtcICEServers2:
  - url: stun:home.amtrend.ru:3478
  - url: turn:home.amtrend.ru:3478
    username: webrtcuser
    password: webrtcpass

paths:
  cam_entrance:
    source: ${RTSP_LINK}
  cam_back_entrance:
    source: ${RTSP_BE_LINK}