FROM arm64v8/ubuntu:22.04

RUN apt-get update && \
    apt-get install -y coturn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["turnserver", "--no-auth", "--listening-port=3478", "--verbose"]
