services:
  django:
    restart: unless-stopped
    container_name: django
    volumes:
      - ../code_site:/code_site
      - ../collect_static:/collect_static
      - ../media:/media
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_django.conf
    command: uwsgi --ini /etc/uwsgi.ini
    links:
      - db
    depends_on:
      - db
    networks:
      - home_default
    env_file:
      - .env
  nginx:
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ../collect_static:/collect_static
      - ../media:/media_static
      - ./sock:/sock
    build:
      context: .
      dockerfile: dockerfiles/docker_nginx.conf
    depends_on:
      - django
    networks:
      - home_default
      - traefik_external
    labels:
      # Common traefik labels
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_external"
      # HTTP -> HTTPS
      - "traefik.http.routers.home-http.entrypoints=http"
      - "traefik.http.routers.home-http.rule=Host(`home.amtrend.ru`)"
      - "traefik.http.routers.home-http.middlewares=http2https@file"
      # HTTPS
      - "traefik.http.routers.home.entrypoints=https"
      - "traefik.http.routers.home.rule=Host(`home.amtrend.ru`)"
      - "traefik.http.routers.home.tls=true"
      - "traefik.http.routers.home.tls.certresolver=le"
      # Local IP (HTTP)
      - "traefik.http.routers.home-local.entrypoints=http"
      - "traefik.http.routers.home-local.rule=Host(`192.168.0.9`)"
  db:
    image: mariadb
    restart: unless-stopped
    container_name: db
    volumes:
      - ../db/initdb:/docker-entrypoint-initdb.d
      - ../db/workdb:/var/lib/mysql
    networks:
      - home_default
    env_file:
      - .env
  redis:
    restart: unless-stopped
    image: redis:alpine
    container_name: redis
    networks:
      - home_default
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    env_file:
      - .env
  celery:
    restart: unless-stopped
    container_name: celery
    build:
      context: .
      dockerfile: dockerfiles/docker_celery.conf
    command: celery -A smart_home worker -n alarm_entrance_worker -Q for_alarm_entrance_task -c 1 --loglevel=info --logfile=logs/celery.log
    volumes:
      - ../code_site:/code
      - ../logs/celery:/code/logs
      - ../media:/media
    networks:
      - home_default
    depends_on:
      - django
      - redis
      - db
    links:
      - redis
      - db
    env_file:
      - .env
  mediamtx:
    build:
      context: .
      dockerfile: dockerfiles/docker_mediamtx.conf
    container_name: mediamtx
    restart: unless-stopped
    volumes:
      - ../media/archive/cam_entrance:/recordings/cam_entrance
      - ../media/archive/cam_b_entrance:/recordings/cam_back_entrance
      - ../media/archive/cam_baby:/recordings/cam_baby
    networks:
      - home_default
    env_file:
      - .env
  coturn:
    image: coturn/coturn:4
    container_name: coturn
    restart: unless-stopped
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    command: ["turnserver", "--fingerprint", "--listening-ip=0.0.0.0",
              "--listening-port=3478", "--external-ip=${EXTERNALIP}",
              "--realm=${SERVICEDOMAIN}", "--lt-cred-mech",
              "--user=${RTCUSER}:${RTCPASS}", "--log-file=stdout"]
    networks:
      - home_default
networks:
  traefik_external:
    external: true
  home_default:
